//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geta.Resurs.Checkout.ConfigurationService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
    public partial class ECommerceError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorTypeDescriptionField;
        
        private int errorTypeIdField;
        
        private bool fixableByYouField;
        
        private string userErrorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorTypeDescription {
            get {
                return this.errorTypeDescriptionField;
            }
            set {
                this.errorTypeDescriptionField = value;
                this.RaisePropertyChanged("errorTypeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorTypeId {
            get {
                return this.errorTypeIdField;
            }
            set {
                this.errorTypeIdField = value;
                this.RaisePropertyChanged("errorTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool fixableByYou {
            get {
                return this.fixableByYouField;
            }
            set {
                this.fixableByYouField = value;
                this.RaisePropertyChanged("fixableByYou");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string userErrorMessage {
            get {
                return this.userErrorMessageField;
            }
            set {
                this.userErrorMessageField = value;
                this.RaisePropertyChanged("userErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ecommerce.resurs.com/v4", ConfigurationName="ConfigurationService.ConfigurationWebService")]
    public interface ConfigurationWebService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message changePasswordRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.changePasswordResponse changePassword(Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.changePasswordResponse> changePasswordAsync(Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message addPasswordRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.addPasswordResponse addPassword(Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.addPasswordResponse> addPasswordAsync(Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message removePasswordRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.removePasswordResponse removePassword(Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.removePasswordResponse> removePasswordAsync(Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message registerEventCallbackRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackResponse registerEventCallback(Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackResponse> registerEventCallbackAsync(Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message getRegisteredEventCallbackRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackResponse getRegisteredEventCallback(Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackResponse> getRegisteredEventCallbackAsync(Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message unregisterEventCallbackRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackResponse unregisterEventCallback(Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackResponse> unregisterEventCallbackAsync(Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message peekInvoiceSequenceRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceResponse peekInvoiceSequence(Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceResponse> peekInvoiceSequenceAsync(Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message setInvoiceSequenceRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceResponse setInvoiceSequence(Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceResponse> setInvoiceSequenceAsync(Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message setInvoiceDataRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataResponse setInvoiceData(Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataResponse> setInvoiceDataAsync(Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ecommerce.resurs.com/v4/msg/configuration) of message getInvoiceDataRequest does not match the default value (http://ecommerce.resurs.com/v4)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Geta.Resurs.Checkout.ConfigurationService.ECommerceError), Action="", Name="ECommerceError", Namespace="http://ecommerce.resurs.com/v4/msg/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataResponse getInvoiceData(Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataResponse> getInvoiceDataAsync(Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePassword", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class changePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newPassword;
        
        public changePasswordRequest() {
        }
        
        public changePasswordRequest(string identifier, string newPassword) {
            this.identifier = identifier;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePasswordResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class changePasswordResponse {
        
        public changePasswordResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addPassword", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class addPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newPassword;
        
        public addPasswordRequest() {
        }
        
        public addPasswordRequest(string identifier, string description, string newPassword) {
            this.identifier = identifier;
            this.description = description;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addPasswordResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class addPasswordResponse {
        
        public addPasswordResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePassword", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class removePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identifier;
        
        public removePasswordRequest() {
        }
        
        public removePasswordRequest(string identifier) {
            this.identifier = identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removePasswordResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class removePasswordResponse {
        
        public removePasswordResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ecommerce.resurs.com/v4/types/configuration")]
    public partial class digestConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private digestAlgorithm digestAlgorithmField;
        
        private string[] digestParametersField;
        
        private string digestSaltField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public digestAlgorithm digestAlgorithm {
            get {
                return this.digestAlgorithmField;
            }
            set {
                this.digestAlgorithmField = value;
                this.RaisePropertyChanged("digestAlgorithm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("digestParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] digestParameters {
            get {
                return this.digestParametersField;
            }
            set {
                this.digestParametersField = value;
                this.RaisePropertyChanged("digestParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string digestSalt {
            get {
                return this.digestSaltField;
            }
            set {
                this.digestSaltField = value;
                this.RaisePropertyChanged("digestSalt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ecommerce.resurs.com/v4/types/configuration")]
    public enum digestAlgorithm {
        
        /// <remarks/>
        MD5,
        
        /// <remarks/>
        SHA1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerEventCallback", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class registerEventCallbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eventType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uriTemplate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string basicAuthUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string basicAuthPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Geta.Resurs.Checkout.ConfigurationService.digestConfiguration digestConfiguration;
        
        public registerEventCallbackRequest() {
        }
        
        public registerEventCallbackRequest(string eventType, string uriTemplate, string basicAuthUserName, string basicAuthPassword, Geta.Resurs.Checkout.ConfigurationService.digestConfiguration digestConfiguration) {
            this.eventType = eventType;
            this.uriTemplate = uriTemplate;
            this.basicAuthUserName = basicAuthUserName;
            this.basicAuthPassword = basicAuthPassword;
            this.digestConfiguration = digestConfiguration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerEventCallbackResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class registerEventCallbackResponse {
        
        public registerEventCallbackResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRegisteredEventCallback", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class getRegisteredEventCallbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eventType;
        
        public getRegisteredEventCallbackRequest() {
        }
        
        public getRegisteredEventCallbackRequest(string eventType) {
            this.eventType = eventType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRegisteredEventCallbackResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class getRegisteredEventCallbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uriTemplate;
        
        public getRegisteredEventCallbackResponse() {
        }
        
        public getRegisteredEventCallbackResponse(string uriTemplate) {
            this.uriTemplate = uriTemplate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unregisterEventCallback", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class unregisterEventCallbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eventType;
        
        public unregisterEventCallbackRequest() {
        }
        
        public unregisterEventCallbackRequest(string eventType) {
            this.eventType = eventType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unregisterEventCallbackResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class unregisterEventCallbackResponse {
        
        public unregisterEventCallbackResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="peekInvoiceSequence", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class peekInvoiceSequenceRequest {
        
        public peekInvoiceSequenceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="peekInvoiceSequenceResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class peekInvoiceSequenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string nextInvoiceNumber;
        
        public peekInvoiceSequenceResponse() {
        }
        
        public peekInvoiceSequenceResponse(string nextInvoiceNumber) {
            this.nextInvoiceNumber = nextInvoiceNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setInvoiceSequence", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class setInvoiceSequenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", IsNullable=true)]
        public string nextInvoiceNumber;
        
        public setInvoiceSequenceRequest() {
        }
        
        public setInvoiceSequenceRequest(string nextInvoiceNumber) {
            this.nextInvoiceNumber = nextInvoiceNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setInvoiceSequenceResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class setInvoiceSequenceResponse {
        
        public setInvoiceSequenceResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ecommerce.resurs.com/v4/types/configuration")]
    public partial class invoiceData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string streetField;
        
        private string zipcodeField;
        
        private string cityField;
        
        private string countryField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        private string homepageField;
        
        private string vatregField;
        
        private string orgnrField;
        
        private bool companytaxnoteField;
        
        private byte[] logotypeField;
        
        private string modifiedbyField;
        
        public invoiceData() {
            this.companytaxnoteField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
                this.RaisePropertyChanged("zipcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string homepage {
            get {
                return this.homepageField;
            }
            set {
                this.homepageField = value;
                this.RaisePropertyChanged("homepage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string vatreg {
            get {
                return this.vatregField;
            }
            set {
                this.vatregField = value;
                this.RaisePropertyChanged("vatreg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string orgnr {
            get {
                return this.orgnrField;
            }
            set {
                this.orgnrField = value;
                this.RaisePropertyChanged("orgnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool companytaxnote {
            get {
                return this.companytaxnoteField;
            }
            set {
                this.companytaxnoteField = value;
                this.RaisePropertyChanged("companytaxnote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=12)]
        public byte[] logotype {
            get {
                return this.logotypeField;
            }
            set {
                this.logotypeField = value;
                this.RaisePropertyChanged("logotype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string modifiedby {
            get {
                return this.modifiedbyField;
            }
            set {
                this.modifiedbyField = value;
                this.RaisePropertyChanged("modifiedby");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setInvoiceData", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class setInvoiceDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Geta.Resurs.Checkout.ConfigurationService.invoiceData invoiceData;
        
        public setInvoiceDataRequest() {
        }
        
        public setInvoiceDataRequest(Geta.Resurs.Checkout.ConfigurationService.invoiceData invoiceData) {
            this.invoiceData = invoiceData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setInvoiceDataResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class setInvoiceDataResponse {
        
        public setInvoiceDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInvoiceData", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class getInvoiceDataRequest {
        
        public getInvoiceDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInvoiceDataResponse", WrapperNamespace="http://ecommerce.resurs.com/v4/msg/configuration", IsWrapped=true)]
    public partial class getInvoiceDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ecommerce.resurs.com/v4/msg/configuration", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Geta.Resurs.Checkout.ConfigurationService.invoiceData invoiceData;
        
        public getInvoiceDataResponse() {
        }
        
        public getInvoiceDataResponse(Geta.Resurs.Checkout.ConfigurationService.invoiceData invoiceData) {
            this.invoiceData = invoiceData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfigurationWebServiceChannel : Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationWebServiceClient : System.ServiceModel.ClientBase<Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService>, Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService {
        
        public ConfigurationWebServiceClient() {
        }
        
        public ConfigurationWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.changePasswordResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.changePassword(Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest request) {
            return base.Channel.changePassword(request);
        }
        
        public void changePassword(string identifier, string newPassword) {
            Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest();
            inValue.identifier = identifier;
            inValue.newPassword = newPassword;
            Geta.Resurs.Checkout.ConfigurationService.changePasswordResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).changePassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.changePasswordResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.changePasswordAsync(Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest request) {
            return base.Channel.changePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.changePasswordResponse> changePasswordAsync(string identifier, string newPassword) {
            Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.changePasswordRequest();
            inValue.identifier = identifier;
            inValue.newPassword = newPassword;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).changePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.addPasswordResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.addPassword(Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest request) {
            return base.Channel.addPassword(request);
        }
        
        public void addPassword(string identifier, string description, string newPassword) {
            Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest();
            inValue.identifier = identifier;
            inValue.description = description;
            inValue.newPassword = newPassword;
            Geta.Resurs.Checkout.ConfigurationService.addPasswordResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).addPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.addPasswordResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.addPasswordAsync(Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest request) {
            return base.Channel.addPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.addPasswordResponse> addPasswordAsync(string identifier, string description, string newPassword) {
            Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.addPasswordRequest();
            inValue.identifier = identifier;
            inValue.description = description;
            inValue.newPassword = newPassword;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).addPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.removePasswordResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.removePassword(Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest request) {
            return base.Channel.removePassword(request);
        }
        
        public void removePassword(string identifier) {
            Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest();
            inValue.identifier = identifier;
            Geta.Resurs.Checkout.ConfigurationService.removePasswordResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).removePassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.removePasswordResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.removePasswordAsync(Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest request) {
            return base.Channel.removePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.removePasswordResponse> removePasswordAsync(string identifier) {
            Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.removePasswordRequest();
            inValue.identifier = identifier;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).removePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.registerEventCallback(Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest request) {
            return base.Channel.registerEventCallback(request);
        }
        
        public void registerEventCallback(string eventType, string uriTemplate, string basicAuthUserName, string basicAuthPassword, Geta.Resurs.Checkout.ConfigurationService.digestConfiguration digestConfiguration) {
            Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest();
            inValue.eventType = eventType;
            inValue.uriTemplate = uriTemplate;
            inValue.basicAuthUserName = basicAuthUserName;
            inValue.basicAuthPassword = basicAuthPassword;
            inValue.digestConfiguration = digestConfiguration;
            Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).registerEventCallback(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.registerEventCallbackAsync(Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest request) {
            return base.Channel.registerEventCallbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackResponse> registerEventCallbackAsync(string eventType, string uriTemplate, string basicAuthUserName, string basicAuthPassword, Geta.Resurs.Checkout.ConfigurationService.digestConfiguration digestConfiguration) {
            Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.registerEventCallbackRequest();
            inValue.eventType = eventType;
            inValue.uriTemplate = uriTemplate;
            inValue.basicAuthUserName = basicAuthUserName;
            inValue.basicAuthPassword = basicAuthPassword;
            inValue.digestConfiguration = digestConfiguration;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).registerEventCallbackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.getRegisteredEventCallback(Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest request) {
            return base.Channel.getRegisteredEventCallback(request);
        }
        
        public string getRegisteredEventCallback(string eventType) {
            Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest();
            inValue.eventType = eventType;
            Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).getRegisteredEventCallback(inValue);
            return retVal.uriTemplate;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.getRegisteredEventCallbackAsync(Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest request) {
            return base.Channel.getRegisteredEventCallbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackResponse> getRegisteredEventCallbackAsync(string eventType) {
            Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.getRegisteredEventCallbackRequest();
            inValue.eventType = eventType;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).getRegisteredEventCallbackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.unregisterEventCallback(Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest request) {
            return base.Channel.unregisterEventCallback(request);
        }
        
        public void unregisterEventCallback(string eventType) {
            Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest();
            inValue.eventType = eventType;
            Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).unregisterEventCallback(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.unregisterEventCallbackAsync(Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest request) {
            return base.Channel.unregisterEventCallbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackResponse> unregisterEventCallbackAsync(string eventType) {
            Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.unregisterEventCallbackRequest();
            inValue.eventType = eventType;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).unregisterEventCallbackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.peekInvoiceSequence(Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest request) {
            return base.Channel.peekInvoiceSequence(request);
        }
        
        public string peekInvoiceSequence() {
            Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest();
            Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).peekInvoiceSequence(inValue);
            return retVal.nextInvoiceNumber;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.peekInvoiceSequenceAsync(Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest request) {
            return base.Channel.peekInvoiceSequenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceResponse> peekInvoiceSequenceAsync() {
            Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.peekInvoiceSequenceRequest();
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).peekInvoiceSequenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.setInvoiceSequence(Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest request) {
            return base.Channel.setInvoiceSequence(request);
        }
        
        public void setInvoiceSequence(string nextInvoiceNumber) {
            Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest();
            inValue.nextInvoiceNumber = nextInvoiceNumber;
            Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).setInvoiceSequence(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.setInvoiceSequenceAsync(Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest request) {
            return base.Channel.setInvoiceSequenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceResponse> setInvoiceSequenceAsync(string nextInvoiceNumber) {
            Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.setInvoiceSequenceRequest();
            inValue.nextInvoiceNumber = nextInvoiceNumber;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).setInvoiceSequenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.setInvoiceData(Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest request) {
            return base.Channel.setInvoiceData(request);
        }
        
        public void setInvoiceData(Geta.Resurs.Checkout.ConfigurationService.invoiceData invoiceData) {
            Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest();
            inValue.invoiceData = invoiceData;
            Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).setInvoiceData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.setInvoiceDataAsync(Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest request) {
            return base.Channel.setInvoiceDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataResponse> setInvoiceDataAsync(Geta.Resurs.Checkout.ConfigurationService.invoiceData invoiceData) {
            Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.setInvoiceDataRequest();
            inValue.invoiceData = invoiceData;
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).setInvoiceDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataResponse Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.getInvoiceData(Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest request) {
            return base.Channel.getInvoiceData(request);
        }
        
        public Geta.Resurs.Checkout.ConfigurationService.invoiceData getInvoiceData() {
            Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest();
            Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataResponse retVal = ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).getInvoiceData(inValue);
            return retVal.invoiceData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataResponse> Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService.getInvoiceDataAsync(Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest request) {
            return base.Channel.getInvoiceDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataResponse> getInvoiceDataAsync() {
            Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest inValue = new Geta.Resurs.Checkout.ConfigurationService.getInvoiceDataRequest();
            return ((Geta.Resurs.Checkout.ConfigurationService.ConfigurationWebService)(this)).getInvoiceDataAsync(inValue);
        }
    }
}
