using System.Collections.Generic;

namespace Geta.Commerce.Payments.PayPal.Helpers
{
    public static class Countries
    {
        public static IEnumerable<Country> All =>
            new[]
            {
                new Country("AW","ABW","Aruba"),
                new Country("AF","AFG","Afghanistan"),
                new Country("AO","AGO","Angola"),
                new Country("AI","AIA","Anguilla"),
                new Country("AX","ALA","Åland Islands"),
                new Country("AL","ALB","Albania"),
                new Country("AD","AND","Andorra"),
                new Country("AN","ANT","Netherlands Antilles"),
                new Country("AE","ARE","United Arab Emirates"),
                new Country("AR","ARG","Argentina"),
                new Country("AM","ARM","Armenia"),
                new Country("AS","ASM","American Samoa"),
                new Country("AQ","ATA","Antarctica"),
                new Country("TF","ATF","French Southern Territories"),
                new Country("AG","ATG","Antigua and Barbuda"),
                new Country("AU","AUS","Australia"),
                new Country("AT","AUT","Austria"),
                new Country("AZ","AZE","Azerbaijan"),
                new Country("BI","BDI","Burundi"),
                new Country("BE","BEL","Belgium"),
                new Country("BJ","BEN","Benin"),
                new Country("BF","BFA","Burkina Faso"),
                new Country("BD","BGD","Bangladesh"),
                new Country("BG","BGR","Bulgaria"),
                new Country("BH","BHR","Bahrain"),
                new Country("BS","BHS","Bahamas"),
                new Country("BA","BIH","Bosnia and Herzegovina"),
                new Country("BL","BLM","Saint Barthélemy"),
                new Country("BY","BLR","Belarus"),
                new Country("BZ","BLZ","Belize"),
                new Country("BM","BMU","Bermuda"),
                new Country("BO","BOL","Bolivia"),
                new Country("BR","BRA","Brazil"),
                new Country("BB","BRB","Barbados"),
                new Country("BN","BRN","Brunei Darussalam"),
                new Country("BT","BTN","Bhutan"),
                new Country("BV","BVT","Bouvet Island"),
                new Country("BW","BWA","Botswana"),
                new Country("CF","CAF","Central African Republic"),
                new Country("CA","CAN","Canada"),
                new Country("CC","CCK","Cocos Islands"),
                new Country("CH","CHE","Switzerland"),
                new Country("CL","CHL","Chile"),
                new Country("CN","CHN","China"),
                new Country("CI","CIV","Côte d'Ivoire"),
                new Country("CM","CMR","Cameroon"),
                new Country("CD","COD","Congo, The Democratic Republic of the"),
                new Country("CG","COG","Congo"),
                new Country("CK","COK","Cook Islands"),
                new Country("CO","COL","Colombia"),
                new Country("KM","COM","Comoros"),
                new Country("CV","CPV","Cape Verde"),
                new Country("CR","CRI","Costa Rica"),
                new Country("CU","CUB","Cuba"),
                new Country("CX","CXR","Christmas Island"),
                new Country("KY","CYM","Cayman Islands"),
                new Country("CY","CYP","Cyprus"),
                new Country("CZ","CZE","Czech Republic"),
                new Country("DE","DEU","Germany"),
                new Country("DJ","DJI","Djibouti"),
                new Country("DM","DMA","Dominica"),
                new Country("DK","DNK","Denmark"),
                new Country("DO","DOM","Dominican Republic"),
                new Country("DZ","DZA","Algeria"),
                new Country("EC","ECU","Ecuador"),
                new Country("EG","EGY","Egypt"),
                new Country("ER","ERI","Eritrea"),
                new Country("EH","ESH","Western Sahara"),
                new Country("ES","ESP","Spain"),
                new Country("EE","EST","Estonia"),
                new Country("ET","ETH","Ethiopia"),
                new Country("FI","FIN","Finland"),
                new Country("FJ","FJI","Fiji"),
                new Country("FK","FLK","Falkland Islands"),
                new Country("FR","FRA","France"),
                new Country("FO","FRO","Faroe Islands"),
                new Country("FM","FSM","Micronesia, Federated States of"),
                new Country("GA","GAB","Gabon"),
                new Country("GB","GBR","United Kingdom"),
                new Country("GE","GEO","Georgia"),
                new Country("GG","GGY","Guernsey"),
                new Country("GH","GHA","Ghana"),
                new Country("GI","GIB","Gibraltar"),
                new Country("GN","GIN","Guinea"),
                new Country("GP","GLP","Guadeloupe"),
                new Country("GM","GMB","Gambia"),
                new Country("GW","GNB","Guinea-Bissau"),
                new Country("GQ","GNQ","Equatorial Guinea"),
                new Country("GR","GRC","Greece"),
                new Country("GD","GRD","Grenada"),
                new Country("GL","GRL","Greenland"),
                new Country("GT","GTM","Guatemala"),
                new Country("GF","GUF","French Guiana"),
                new Country("GU","GUM","Guam"),
                new Country("GY","GUY","Guyana"),
                new Country("HK","HKG","Hong Kong"),
                new Country("HM","HMD","Heard Island and McDonald Islands"),
                new Country("HN","HND","Honduras"),
                new Country("HR","HRV","Croatia"),
                new Country("HT","HTI","Haiti"),
                new Country("HU","HUN","Hungary"),
                new Country("ID","IDN","Indonesia"),
                new Country("IM","IMN","Isle of Man"),
                new Country("IN","IND","India"),
                new Country("IO","IOT","British Indian Ocean Territory"),
                new Country("IE","IRL","Ireland"),
                new Country("IR","IRN","Iran, Islamic Republic of"),
                new Country("IQ","IRQ","Iraq"),
                new Country("IS","ISL","Iceland"),
                new Country("IL","ISR","Israel"),
                new Country("IT","ITA","Italy"),
                new Country("JM","JAM","Jamaica"),
                new Country("JE","JEY","Jersey"),
                new Country("JO","JOR","Jordan"),
                new Country("JP","JPN","Japan"),
                new Country("KZ","KAZ","Kazakhstan"),
                new Country("KE","KEN","Kenya"),
                new Country("KG","KGZ","Kyrgyzstan"),
                new Country("KH","KHM","Cambodia"),
                new Country("KI","KIR","Kiribati"),
                new Country("KN","KNA","Saint Kitts and Nevis"),
                new Country("KR","KOR","Korea, Republic of"),
                new Country("KW","KWT","Kuwait"),
                new Country("LA","LAO","Lao, People's Democratic Republic"),
                new Country("LB","LBN","Lebanon"),
                new Country("LR","LBR","Liberia"),
                new Country("LY","LBY","Libyan Arab Jamahiriya"),
                new Country("LC","LCA","Saint Lucia"),
                new Country("LI","LIE","Liechtenstein"),
                new Country("LK","LKA","Sri Lanka"),
                new Country("LS","LSO","Lesotho"),
                new Country("LT","LTU","Lithuania"),
                new Country("LU","LUX","Luxembourg"),
                new Country("LV","LVA","Latvia"),
                new Country("MO","MAC","Macau"),
                new Country("MF","MAF","Saint Martin"),
                new Country("MA","MAR","Morocco"),
                new Country("MC","MCO","Monaco"),
                new Country("MD","MDA","Moldova, Republic of"),
                new Country("MG","MDG","Madagascar"),
                new Country("MV","MDV","Maldives"),
                new Country("MX","MEX","Mexico"),
                new Country("MH","MHL","Marshall Islands"),
                new Country("MK","MKD","Macedonia, The Former Yugoslav Republic of"),
                new Country("ML","MLI","Mali"),
                new Country("MT","MLT","Malta"),
                new Country("MM","MMR","Myanmar"),
                new Country("ME","MNE","Montenegro"),
                new Country("MN","MNG","Mongolia"),
                new Country("MP","MNP","Northern Mariana Islands"),
                new Country("MZ","MOZ","Mozambique"),
                new Country("MR","MRT","Mauritania"),
                new Country("MS","MSR","Montserrat"),
                new Country("MQ","MTQ","Martinique"),
                new Country("MU","MUS","Mauritius"),
                new Country("MW","MWI","Malawi"),
                new Country("MY","MYS","Malaysia"),
                new Country("YT","MYT","Mayotte"),
                new Country("NA","NAM","Namibia"),
                new Country("NC","NCL","New Caledonia"),
                new Country("NE","NER","Niger"),
                new Country("NF","NFK","Norfolk Island"),
                new Country("NG","NGA","Nigeria"),
                new Country("NI","NIC","Nicaragua"),
                new Country("NU","NIU","Niue"),
                new Country("NL","NLD","Netherlands"),
                new Country("NO","NOR","Norway"),
                new Country("NP","NPL","Nepal"),
                new Country("NR","NRU","Nauru"),
                new Country("NZ","NZL","New Zealand"),
                new Country("OM","OMN","Oman"),
                new Country("PK","PAK","Pakistan"),
                new Country("PA","PAN","Panama"),
                new Country("PN","PCN","Pitcairn"),
                new Country("PE","PER","Peru"),
                new Country("PH","PHL","Philippines"),
                new Country("PW","PLW","Palau"),
                new Country("PG","PNG","Papua New Guinea"),
                new Country("PL","POL","Poland"),
                new Country("PR","PRI","Puerto Rico"),
                new Country("KP","PRK","Korea, Democratic People's Republic of"),
                new Country("PT","PRT","Portugal"),
                new Country("PY","PRY","Paraguay"),
                new Country("PS","PSE","Palestinian Territory"),
                new Country("PF","PYF","French Polynesia"),
                new Country("QA","QAT","Qatar"),
                new Country("RE","REU","Réunion"),
                new Country("RO","ROU","Romania"),
                new Country("RU","RUS","Russian Federation"),
                new Country("RW","RWA","Rwanda"),
                new Country("SA","SAU","Saudi Arabia"),
                new Country("SD","SDN","Sudan"),
                new Country("SN","SEN","Senegal"),
                new Country("SG","SGP","Singapore"),
                new Country("GS","SGS","South Georgia and the South Sandwich Islands"),
                new Country("SH","SHN","Saint Helena"),
                new Country("SJ","SJM","Svalbard and Jan Mayen"),
                new Country("SB","SLB","Solomon Islands"),
                new Country("SL","SLE","Sierra Leone"),
                new Country("SV","SLV","El Salvador"),
                new Country("SM","SMR","San Marino"),
                new Country("SO","SOM","Somalia"),
                new Country("PM","SPM","Saint Pierre and Miquelon"),
                new Country("RS","SRB","Serbia"),
                new Country("ST","STP","Sao Tome and Principe "),
                new Country("SR","SUR","Suriname"),
                new Country("SK","SVK","Slovakia"),
                new Country("SI","SVN","Slovenia"),
                new Country("SE","SWE","Sweden"),
                new Country("SZ","SWZ","Swaziland"),
                new Country("SC","SYC","Seychelles"),
                new Country("SY","SYR","Syrian Arab Republic"),
                new Country("TC","TCA","Turks and Caicos Islands"),
                new Country("TD","TCD","Chad"),
                new Country("TG","TGO","Togo"),
                new Country("TH","THA","Thailand"),
                new Country("TJ","TJK","Tajikistan"),
                new Country("TK","TKL","Tokelau"),
                new Country("TM","TKM","Turkmenistan"),
                new Country("TL","TLS","Timor-Leste"),
                new Country("TO","TON","Tonga"),
                new Country("TT","TTO","Trinidad and Tobago"),
                new Country("TN","TUN","Tunisia"),
                new Country("TR","TUR","Turkey"),
                new Country("TV","TUV","Tuvalu"),
                new Country("TW","TWN","Taiwan"),
                new Country("TZ","TZA","Tanzania, United Republic of"),
                new Country("UG","UGA","Uganda"),
                new Country("UA","UKR","Ukraine"),
                new Country("UM","UMI","United States Minor Outlying Islands"),
                new Country("UY","URY","Uruguay"),
                new Country("US","USA","United States"),
                new Country("UZ","UZB","Uzbekistan"),
                new Country("VA","VAT","Holy See (Vatican City State)"),
                new Country("VC","VCT","Saint Vincent and the Grenadines"),
                new Country("VE","VEN","Venezuela"),
                new Country("VG","VGB","Virgin Islands, British"),
                new Country("VI","VIR","Virgin Islands, U.S."),
                new Country("VN","VNM","Viet Nam"),
                new Country("VU","VUT","Vanuatu"),
                new Country("WF","WLF","Wallis and Futuna"),
                new Country("WS","WSM","Samoa"),
                new Country("YE","YEM","Yemen"),
                new Country("ZA","ZAF","South Africa"),
                new Country("ZM","ZMB","Zambia"),
                new Country("ZW","ZWE","Zimbabwe")
            };
    }
}